### PR TITLE
libstoragemgmt: Add support for retrieving firmware versions from storage targets

### PR DESCRIPTION
**Pull request by joehandzik**
Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

### CODE REVIEW

**Comment by joehandzik** [comment]
FYI, only tested with an HPE smart array Gen9 controller and some of the generic interfaces that I implemented. Hopefully the non-HPE stuff works fine, since I never advertise support for the firmware retrieval for those plugins.

**Comment by joehandzik** [comment]
Seeing failures on the top two plugins that don't seem to be things I can fix. One is:

LsmError: NETWORK_CONNREFUSED(140): Connection refused 

The other one was an argument count mismatch (I would copy and paste, but for some reason my corporate firewall is having a fit that I'm accessing the "Details" links now). Any ideas? I don't figure those failures are something I could induce, but I've been wrong about such things before.

**Comment by cathay4t** [comment]
@joehandzik Please ignore the NETWORK_CONNREFUSED failure, the EMC VNX device is offline.
For the targetd failure, I will look into it.

**Comment by cathay4t** [comment]
Sure. I will prepare the MegaRAID part also.

**Comment by joehandzik** [comment]
Thanks, @cathay4t. Keep me updated if there's something I need to change here, otherwise I'll assume that the test failures were due to something other than my code changes.

**Comment by cathay4t** [comment]
@joehandzik I created pull request to your branch which include MegaRAID support
on this function:
https://github.com/joehandzik/libstoragemgmt/pull/1

**Comment by joehandzik** [comment]
All comments should be addressed, and I left a comment on your PR. We could migrate @tasleson's point into this main thread too...summary is that I'm all for what he's suggestion, you guys just need to tell me what you want. I think a fine plan would be to leave this PR as-is for now, and converge all this code into the base set of system structures in v2.0. Everything I'm adding from here on is something I actually need to know about the storage for one of several scale-out solutions that I work with, so I actually *need* these upstream as soon as possible.

**Comment by cathay4t** [comment]
@tasleson How about we create new branch 'v1.x' on upstream repo where we keep 1.x binary
compatibility?
Joe could create pull request to master branch while we maintain the 1.x branch.

**Comment by cathay4t** [comment]
@joehandzik Tony found a way to both:
1. Don't waste on extra call on `lsm_system_fw_version_get()`.
2. Keep 1.x binary compatibility.

by caching firmware version in  opaque struct lsm_system when `lsm_system_list()`.

Let me create new pull request base on your existing works to make an demonstration.

**Comment by joehandzik** [comment]
Ok, sounds good. I'll emulate in the other PR once you're done. Thanks for the assistance here.

Joe

On Sep 17, 2015, at 8:42 AM, Gri Ge <notifications@github.com<mailto:notifications@github.com>> wrote:


@joehandzik<https://github.com/joehandzik> Tony found a way to both:
1. Don't waste on extra call on lsm_system_fw_version_get().
2. Keep 1.x binary compatibility.

by caching firmware version in opaque struct lsm_system when lsm_system_list().

Let me create new pull request base on your existing works to make an demonstration.

�

**Comment by joehandzik** [comment]
Didn't get to it today, but I'll add the 1.3 stuff in on a separate PR, which you can integrate in first, and then I'll rebase the existing PRs to put both methods in the 1.3 ops structure. Sound fair?

**Comment by joehandzik** [comment]
@cathay4t, updated this PR to include the 1.3 change instead. Thought about a separate commit, but then realized it would define a structure without any elements in it...seemed kinda silly. Hope this looks alright!

**Comment by joehandzik** [comment]
@cathay4t I just pulled in your PR against my branch with a cherry-pick, easier than dealing with trying to reconcile whatever issue wouldn't allow me to merge the PR into my branch. I think this one is ready, finally.

**Comment by cathay4t** [comment]
@joehandzik Sorry for the overlap. I created new pull request base on your work
https://github.com/libstorage/libstoragemgmt/pull/56
It's not commit ready yet,  but I could really use your valuable comments on the
API design. As you requested, no extra external call is required for
querying firmware version, it's cached in lsm_system instance.

**Comment by cathay4t** [comment]
Closed as requesting functions got merged by pull request #56

**Pull request closed without merging**
