### PR TITLE
Simulator C plugin: Use sqlite3 for state tracking.

### PR DESCRIPTION
**Pull request by cathay4t**
**Please review PR #188 first**
Just make sure `simc://` and `sim://` are using the same file for state tracing.

### CODE REVIEW

**Comment by cathay4t** [comment]
The sqlite3 using by travis CI is too old to have `sqlite3_errstr()`. Will find a workaround.

**Comment by cathay4t** [comment]
The SQL function `printf()` introduced since 3.8+ version  is not exits in RHEL 6(3.6.20) or Ubuntu 12.04(sqlite 3.7.9).

Need to find workaround.

**Comment by cathay4t** [comment]
This command will crash plugin on RHEL 6 and Ubuntu 12.04:
```
lsmcli -u simc:// fs-export --fs FS_ID_00001 --rw-host localhost
```
Need investigation.

**Comment by cathay4t** [comment]
Current travis CI failure is caused by difference of -1 on uint64_t on RHEL 7 and RHEL 6/Ubuntu 12.04.
Still investigating.

**Comment by cathay4t** [comment]
Make check pass on RHEL 6 and Archlinux.

**Comment by cathay4t** [comment]
@tasleson PR is ready for review. Thank you.

**Comment by tasleson** [comment]
@cathay4t `make check` and `make distcheck` work, but `make rpm` fails (on F24):

```
utils.c: In function '_md5':
utils.c:61:22: warning: pointer targets in passing argument 1 of 'strlen' differ in signedness [-Wpointer-sign]
     MD5(data, strlen(data), digest);
                      ^~~~
In file included from utils.c:21:0:
/usr/include/string.h:394:15: note: expected 'const char *' but argument is of type 'const unsigned char *'
 extern size_t strlen (const char *__s)
               ^~~~~~
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../c_binding/include -I./c_binding/include -DHAVE_CONFIG_H    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c -o db.o db.c
In file included from db_table_init.h:22:0,
                 from db.c:33:
db.c: In function '_sys_version':
db.h:28:61: warning: pointer targets in passing argument 1 of '_md5' differ in signedness [-Wpointer-sign]
 #define _DB_VERSION                                         "4.0"
                                                             ^
db.c:413:10: note: in expansion of macro '_DB_VERSION'
     _md5(_DB_VERSION, version_md5);
          ^~~~~~~~~~~
In file included from db.h:26:0,
                 from db.c:32:
utils.h:150:6: note: expected 'const unsigned char *' but argument is of type 'char *'
 void _md5(const unsigned char *data, char *out_hash);
      ^~~~
db.c:413:23: warning: pointer targets in passing argument 2 of '_md5' differ in signedness [-Wpointer-sign]
     _md5(_DB_VERSION, version_md5);
                       ^~~~~~~~~~~
In file included from db.h:26:0,
                 from db.c:32:
utils.h:150:6: note: expected 'char *' but argument is of type 'unsigned char *'
 void _md5(const unsigned char *data, char *out_hash);
      ^~~~
db.c: In function '_db_sim_xxx_of_sim_id':
db.c:973:9: error: format not a string literal and no format arguments [-Werror=format-security]
         _lsm_err_msg_set(err_msg, not_found_err_str);
         ^~~~~~~~~~~~~~~~
db.c:987:9: error: format not a string literal and no format arguments [-Werror=format-security]
         _lsm_err_msg_set(err_msg, not_found_err_str);
         ^~~~~~~~~~~~~~~~

```
Not sure at the moment why, please take a peek.  Once you get a source rpm, run coverity on it.  Thanks!

**Comment by cathay4t** [comment]
@tasleson Thanks for pointing that out. Fixed.
 * 'make rpm' pass without warning on RHEL 6, RHEL 7, Fedora 24, Archlinux.
 * coverity pass on simc codes.

**Comment by tasleson** [comment]
@cathay4t OK, `make check`, `make distcheck`, `make rpm` work.  I ran coverity and found:

```
Error: CPPCHECK_WARNING (CWE-843): [#def2]
libstoragemgmt-1.3.4/plugin/simc/db.c:802: error[va_list_usedBeforeStarted]: va_list 'arg' used before va_start() was called.
#  800|               goto out;
#  801|           }
#  802|->         key_str = va_arg(arg, const char *);
#  803|           if (key_str != NULL)
#  804|               value_str = va_arg(arg, const char *);

Error: CPPCHECK_WARNING (CWE-843): [#def3]
libstoragemgmt-1.3.4/plugin/simc/db.c:804: error[va_list_usedBeforeStarted]: va_list 'arg' used before va_start() was called.
#  802|           key_str = va_arg(arg, const char *);
#  803|           if (key_str != NULL)
#  804|->             value_str = va_arg(arg, const char *);
#  805|       }
#  806|       va_end(arg);

Error: CPPCHECK_WARNING (CWE-843): [#def4]
libstoragemgmt-1.3.4/plugin/simc/db.c:806: error[va_list_usedBeforeStarted]: va_list 'arg' used before va_start() was called.
#  804|               value_str = va_arg(arg, const char *);
#  805|       }
#  806|->     va_end(arg);
#  807|   
#  808|       /* Remove the trailing ", " */

Error: DC.WEAK_CRYPTO: [#def5]
libstoragemgmt-1.3.4/test/tester.c:109: dont_call: "rand" should not be used for security related applications, as linear congruential algorithms are too easy to break.
libstoragemgmt-1.3.4/test/tester.c:109: remediation: Use a compliant random number generator, such as "/dev/random" or "/dev/urandom" on Unix-like systems, and "CryptGenRandom" on Windows.
#  107|       if( buff && (len > 1) ) {
#  108|           for(i = 0; i < (len - 1); ++i) {
#  109|->             buff[i] = 97 + rand()%26;
#  110|           }
#  111|           buff[len-1] = '\0';

Error: CHECKED_RETURN (CWE-252): [#def6]
libstoragemgmt-1.3.4/test/tester.c:188: check_return: Calling "getchar()" without checking return value. This library function may fail and return an error code. [Note: The source code implementation of the function has been overridden by a builtin model.]
#  186|           if( getenv("LSM_DEBUG_PLUGIN") ) {
#  187|               printf("Attach debugger to plug-in, press <return> when ready...");
#  188|->             getchar();
#  189|           }
#  190|       }

Error: CLANG_WARNING: [#def7]
libstoragemgmt-1.3.4/test/tester.c:2212:21: warning: Null pointer passed as an argument to a 'nonnull' parameter
#        fail_unless(memcmp(d, debug_data, debug_size) == 0);
#                    ^
/usr/include/check.h:248:18: note: expanded from macro 'ck_assert_msg'
#  _ck_assert_msg(expr, __FILE__, __LINE__,\
#                 ^
libstoragemgmt-1.3.4/test/tester.c:2204:5: note: Taking true branch
#    if( e ) {
#    ^
libstoragemgmt-1.3.4/test/tester.c:2209:9: note: Value assigned to 'debug_data'
#        debug_data = lsm_error_debug_data_get(e, &debug_size);
#        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libstoragemgmt-1.3.4/test/tester.c:2210:21: note: Assuming 'debug_data' is equal to null
#        fail_unless(debug_data != NULL);
#                    ^
/usr/include/check.h:248:18: note: expanded from macro 'ck_assert_msg'
#  _ck_assert_msg(expr, __FILE__, __LINE__,\
#                 ^
libstoragemgmt-1.3.4/test/tester.c:2212:21: note: Null pointer passed as an argument to a 'nonnull' parameter
#        fail_unless(memcmp(d, debug_data, debug_size) == 0);
#                    ^         ~~~~~~~~~~
/usr/include/check.h:248:18: note: expanded from macro 'ck_assert_msg'
#  _ck_assert_msg(expr, __FILE__, __LINE__,\
#                 ^
# 2210|           fail_unless(debug_data != NULL);
# 2211|           fail_unless(debug_size == sizeof(d));
# 2212|->         fail_unless(memcmp(d, debug_data, debug_size) == 0);
# 2213|           fail_unless( LSM_ERR_OK == lsm_error_free(e) );
# 2214|       }

Error: NO_EFFECT (CWE-398): [#def8]
libstoragemgmt-1.3.4/test/tester.c:2335: unsigned_compare: This less-than-zero comparison of an unsigned value is never true. "i < 0UL".
libstoragemgmt-1.3.4/test/tester.c:2335: unsigned_conversion: "i" is converted to an unsigned type because it's compared to an unsigned constant.
# 2333|   
# 2334|           for( i = 0;
# 2335|->             i < sizeof(expected_absent)/sizeof(expected_absent[0]);
# 2336|               ++i) {
# 2337|   

Error: RESOURCE_LEAK (CWE-772): [#def9]
libstoragemgmt-1.3.4/test/tester.c:3291: alloc_arg: "lsm_local_disk_list" allocates memory that is stored into "lsm_err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: alloc_fn: Storage is returned from allocation function "lsm_error_create".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: alloc_fn: Storage is returned from allocation function "calloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: var_assign: Assigning: "err" = "calloc(1UL, 56UL)".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:369:5: return_alloc: Returning allocated memory "err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: var_assign: Assigning: "*lsm_err" = "lsm_error_create(rc, err_msg, NULL, NULL, NULL, 0U)".
libstoragemgmt-1.3.4/test/tester.c:3296: leaked_storage: Variable "lsm_err" going out of scope leaks the storage it points to.
# 3294|                   "disk_paths");
# 3295|       lsm_string_list_free(disk_paths);
# 3296|-> }
# 3297|   END_TEST
# 3298|   

Error: RESOURCE_LEAK (CWE-772): [#def10]
libstoragemgmt-1.3.4/test/tester.c:3381: alloc_arg: "lsm_local_disk_vpd83_search" allocates memory that is stored into "disk_path_list".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:318:5: alloc_fn: Storage is returned from allocation function "lsm_string_list_alloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:134:5: alloc_fn: Storage is returned from allocation function "malloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:134:5: var_assign: Assigning: "rc" = "malloc(16UL)".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:148:5: return_alloc: Returning allocated memory "rc".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:318:5: var_assign: Assigning: "*disk_path_list" = "lsm_string_list_alloc(0U)".
libstoragemgmt-1.3.4/test/tester.c:3393: leaked_storage: Variable "disk_path_list" going out of scope leaks the storage it points to.
# 3391|                   "NULL when searching for VALID_BUT_NOT_EXIST_VPD83");
# 3392|   
# 3393|-> }
# 3394|   END_TEST
# 3395|   

Error: RESOURCE_LEAK (CWE-772): [#def11]
libstoragemgmt-1.3.4/test/tester.c:3381: alloc_arg: "lsm_local_disk_vpd83_search" allocates memory that is stored into "lsm_err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:371:13: alloc_fn: Storage is returned from allocation function "lsm_error_create".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: alloc_fn: Storage is returned from allocation function "calloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: var_assign: Assigning: "err" = "calloc(1UL, 56UL)".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:369:5: return_alloc: Returning allocated memory "err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:371:13: var_assign: Assigning: "*lsm_err" = "lsm_error_create(rc, err_msg, NULL, NULL, NULL, 0U)".
libstoragemgmt-1.3.4/test/tester.c:3393: leaked_storage: Variable "lsm_err" going out of scope leaks the storage it points to.
# 3391|                   "NULL when searching for VALID_BUT_NOT_EXIST_VPD83");
# 3392|   
# 3393|-> }
# 3394|   END_TEST
# 3395|   

Error: RESOURCE_LEAK (CWE-772): [#def12]
libstoragemgmt-1.3.4/test/tester.c:3442: alloc_arg: "lsm_local_disk_vpd83_get" allocates memory that is stored into "vpd83".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:428:9: alloc_fn: Storage is returned from allocation function "strdup".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:428:9: var_assign: Assigning: "*vpd83" = "strdup(tmp_vpd83)".
libstoragemgmt-1.3.4/test/tester.c:3459: leaked_storage: Variable "vpd83" going out of scope leaks the storage it points to.
# 3457|                   "been set with non-NULL error message when disk not exist");
# 3458|       lsm_error_free(lsm_err);
# 3459|-> }
# 3460|   END_TEST
# 3461|   

Error: RESOURCE_LEAK (CWE-772): [#def13]
libstoragemgmt-1.3.4/test/tester.c:3811: alloc_arg: "lsm_local_disk_list" allocates memory that is stored into "lsm_err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: alloc_fn: Storage is returned from allocation function "lsm_error_create".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: alloc_fn: Storage is returned from allocation function "calloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: var_assign: Assigning: "err" = "calloc(1UL, 56UL)".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:369:5: return_alloc: Returning allocated memory "err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: var_assign: Assigning: "*lsm_err" = "lsm_error_create(rc, err_msg, NULL, NULL, NULL, 0U)".
libstoragemgmt-1.3.4/test/tester.c:3811: leaked_storage: Variable "lsm_err" going out of scope leaks the storage it points to.
# 3809|   START_TEST(test_local_disk_ident_led)
# 3810|   {
# 3811|->     _TEST_LOCAL_DISK_LED(lsm_local_disk_ident_led_on,
# 3812|                            lsm_local_disk_ident_led_off);
# 3813|   }

Error: RESOURCE_LEAK (CWE-772): [#def14]
libstoragemgmt-1.3.4/test/tester.c:3818: alloc_arg: "lsm_local_disk_list" allocates memory that is stored into "lsm_err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: alloc_fn: Storage is returned from allocation function "lsm_error_create".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: alloc_fn: Storage is returned from allocation function "calloc".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:338:23: var_assign: Assigning: "err" = "calloc(1UL, 56UL)".
libstoragemgmt-1.3.4/c_binding/lsm_datatypes.cpp:369:5: return_alloc: Returning allocated memory "err".
libstoragemgmt-1.3.4/c_binding/lsm_local_disk.c:610:13: var_assign: Assigning: "*lsm_err" = "lsm_error_create(rc, err_msg, NULL, NULL, NULL, 0U)".
libstoragemgmt-1.3.4/test/tester.c:3818: leaked_storage: Variable "lsm_err" going out of scope leaks the storage it points to.
# 3816|   START_TEST(test_local_disk_fault_led)
# 3817|   {
# 3818|->     _TEST_LOCAL_DISK_LED(lsm_local_disk_fault_led_on,
# 3819|                            lsm_local_disk_fault_led_off);
# 3820|   }
```

**Comment by cathay4t** [comment]
@tasleson I got the same covscan report, just forgot to mention:
 * The `va_list 'arg' used before va_start() was called.` errors are faults alarm. I do have `va_start()` before them. The fixed this in 8.5 covscan.
 * All errors in `tester.c` is for old code, I don't want to fix them in current PR.

**Comment by tasleson** [comment]
@cathay4t  Nice work, thanks!

**Pull request merged**
