### PR TITLE
Clean up code covscan warnings.

### PR DESCRIPTION
**Pull request by cathay4t**
Fix issue found in https://gist.github.com/cathay4t/96335dddbf4399755b091cda69fffb02

### CODE REVIEW

**Comment by cathay4t** [comment]
@joehandzik This PR contain big changes on your ATA health status code. Could you take some time to review the code and try it in your lab? Thank you.

**Comment by joehandzik** [comment]
@cathay4t I'll take a look sometime this week, though running on a machine in my lab may be tricky. I'll see what I can accomplish.

**Comment by cathay4t** [comment]
@joehandzik Thanks for the review. When we need use ata pass through elsewhere, we could move those codes out to cover the new need.

**Comment by cathay4t** [comment]
Merged.

**Pull request merged**
