### PR TITLE
RPM SPEC clean up

### PR DESCRIPTION
**Pull request by cathay4t**
* Only keep the Fedora version rpm spec.
 * Add new sub-package for arcconf plugin.

### CODE REVIEW

**Comment by jumitche** [comment]
Does this also package the big pile of man3 entries that i think are produced by the recent documentation changes? as that and arcconf are the two unpackaged things on head right now

**Comment by cathay4t** [comment]
@jumitche Yes. This PR include man page changes and arcconf sub plugin. I just need to rebase to current master tomorrow.

**Comment by cathay4t** [comment]
@jumitche Rebased to current master.

**Comment by tasleson** [comment]
@cathay4t When I do `make rpm` I get the following error on my F26 system, I don't think it related to these changes, but if you could take a look that would be great!

***Note:*** `make distcheck` works fine

```
  volume_raid_info: {count: 2, number_items: 10, total_time: 0.04863619804382324}
  volume_read_cache_policy_update: {count: 2, number_items: 0, total_time: 0.04555225372314453}
  volume_replicate: {count: 5, number_items: 0, total_time: 0.18248462677001953}
  volume_replicate_range: {count: 2, number_items: 0, total_time: 0.07158660888671875}
  volume_replicate_range_block_size: {count: 2, number_items: 0, total_time: 0.015557050704956055}
  volume_resize: {count: 1, number_items: 0, total_time: 0.05986762046813965}
  volume_unmask: {count: 2, number_items: 0, total_time: 0.05412602424621582}
  volume_write_cache_policy_update: {count: 3, number_items: 0, total_time: 0.05289864540100098}
  volumes: {count: 99, number_items: 12, total_time: 1.3844561576843262}
  volumes_accessible_by_access_group: {count: 3, number_items: 0, total_time: 0.050644636154174805}
/home/tasleson/rpmbuild/BUILD/libstoragemgmt-1.5.0-1.fc26-python3/test/test_include.sh: line 88:  3589 Killed                  env --unset=LSM_VALGRIND valgrind --quiet --leak-check=full --show-reachable=no --show-possibly-lost=no --trace-children=yes --error-exitcode=99 --errors-for-leak-kinds=definite --log-file=/tmp/8726/logs//mem_leak__lsmd_%p /tmp/8726/bin//lsmd --plugindir=/tmp/8726/plugins/ --socketdir=/tmp/8726/ipc --confdir=/tmp/8726/config/ -d -v > /tmp/8726/logs//lsmd.log
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: error: source directory already configured; run "make distclean" there first
FAIL test/runtests.sh (exit status: 1)

+ exit 1
error: Bad exit status from /var/tmp/rpm-tmp.3Y41Ot (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.3Y41Ot (%check)
make: *** [Makefile:1309: rpm] Error 1

```

**Comment by cathay4t** [comment]
@tasleson I reproduced this problem and still debuging it.
Since travis CI does not have python3(travis CI is using ubuntu 12.04 which has no python3 yet) enable, we didn't got error from CI.

**Comment by cathay4t** [comment]
And the `make distcheck` does not include python3 test.

**Comment by cathay4t** [comment]
Found the root cause.
The configure script checks `config.status` file if pwd is not source folder.

After copy the source folder to tmp folder for py2 vs py3 test, a lot error raise up. Still digging.

**Comment by cathay4t** [comment]
The case failure is caused by NFS plugin in python3 vs python2 test. Fixed.

**Comment by cathay4t** [comment]
@tasleson Patchs are ready for review now. `make rpm` works well on Fedora rawhide now.

**Comment by tasleson** [comment]
@cathay4t  Thanks Gris!

**Pull request merged**
