### PR TITLE
HPE Smart Array: Handle the full variety of ways that system cache ca…

### PR DESCRIPTION
**Pull request by joehandzik**
…n be reported by hpssacli

Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

### CODE REVIEW

**Comment by joehandzik** [comment]
Our lovely cli utility supports multiple terms for the controller cache. Apologies!

**Comment by joehandzik** [comment]
nstor strikes again!

**Comment by tasleson** [comment]
@joehandzik I looked at this nstor failure some more today, it's the same issue we've hit before.  I will try and reach out to nexenta and see if we can get to root cause.

**Comment by cathay4t** [comment]
The nstor error is caused by empty VPD83 issue reported by plugin_test.
If we failed to find a way to get nstor vpd83, we could update `plugin_test.py` to skip vpd83 test on nstor URI and mark it as known issue.

**Comment by joehandzik** [comment]
Any thoughts on this guy? Or do you want to wait on it until I can rebase in a fix for the nstor failures?

**Comment by tasleson** [comment]
@joehandzik Thanks for the fix!

**Comment by tasleson** [comment]
@joehandzik We are going to change nstor from failure to known issue here shortly.  Disregard any failures when the error is missing vpd83.

**Pull request merged**
