### PR TITLE
lsmcli and simarray: Fix disk_location usage to reflect change to loc…

### PR DESCRIPTION
**Pull request by joehandzik**
…ation

The name of the 'disk_location' attribute was changed to 'location', updating remaining uses of 'disk_location'.

Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

### CODE REVIEW

**Comment by tasleson** [comment]
@joehandzik I think you should bump the db version for this too.

**Comment by joehandzik** [comment]
@tasleson Done. In general, when should that VERSION value be changed? When elements of the database are added/deleted/changed?

**Comment by tasleson** [comment]
@joehandzik I would say anytime a schema change occurs or a change that will cause the code unexpectedly to fail.

**Comment by cathay4t** [comment]
Merged. Thanks Joe!

**Pull request merged**
