### PR TITLE
[PATCH V3] Automake 1.15 and python 2.7.9 fix

### PR DESCRIPTION
**Pull request by cathay4t**
Fix 'make check' for automake 1.15+ and python 2.7.9+.

Please refer to issue #75  and #78 for detail.

The branch is based on https://github.com/libstorage/libstoragemgmt/pull/71 please only review the last 4 patches.

### CODE REVIEW

**Comment by cathay4t** [comment]
Please hold. It seems the valgrind in travis system(Ubuntu 12.04.5) does not support `--errors-for-leak-kinds=definite` optoin. Investigating a workaround.

**Comment by cathay4t** [comment]
Fixed travis CI issue.

**Comment by cathay4t** [comment]
@tasleson I split some test bash functions to `test_include.sh` which might be helpfull on your CI test. Still a demo yet, can you check the `DEMO: Separate bash test functions out.` patch and let me konw if any changes required to suit your needs.

**Comment by tasleson** [comment]
@cathay4t the function `lsm_test_base_install` has a parameter `plugin_type`.  So you cannot install both C and Python plugins at same time?  I see the constant for all is commented out...

I will give it a try tomorrow.

**Comment by cathay4t** [comment]
I could add `LSM_TEST_INSTALL_ALL_PLUGINS` back if you need it, just comment it out as I don't actually use it in `runtest.sh`

**Comment by cathay4t** [comment]
V2 patch set uploaded.

Changes in V2:
* Rewrite test setup scripts to use `test_include.sh` which could/might be used by other test tool.
* Fixed python 2.7.9+ argparser issue.

**Comment by cathay4t** [comment]
Rebased to lastest PR #71

**Comment by cathay4t** [comment]
Rebased to lastest PR #71

**Comment by cathay4t** [comment]
V3 patch set uploaded.

Changes in V3:
* Add rpm SPEC change for moving test-suit.log to top folder.
* Fix typo.

**Comment by tasleson** [comment]
I reviewed the last 5 commits, these changes look good.

**Comment by cathay4t** [comment]
Rebased to #71

**Pull request merged**
