### PR TITLE
New release 1.4.0

### PR DESCRIPTION
**Pull request by cathay4t**
@tasleson @joehandzik Any thing you want to add before tag 1.4.0?

### CODE REVIEW

**Comment by cathay4t** [comment]
The document improvement and glib replacement have to wait 1.4.1.

**Comment by joehandzik** [comment]
Nope, nothing from me yet. Thanks for checking!

**Comment by cathay4t** [comment]
@tasleson Do you know why the CI failed after a successful rerun?
```
2017-02-20 03:18:27.259506: pid: 32089: Attempting connection to 104.131.247.234:443
2017-02-20 03:18:27.464111: pid: 32089: Connected!
2017-02-20 03:18:42.881009: pid: 32089: Running test for https://github.com/cathay4t/libstoragemgmt.git master megaraid_rh_lab
git|https://github.com/cathay4t/libstoragemgmt.git|master|megaraid://| exited with 0
```

**Comment by tasleson** [comment]
I'm not sure what's going on here.  The CI service shows that the client serving `megaraid_rh_lab` has connected and disconnected > 2500 times.  That coupled with some TBD bug is causing the node_manager.py process to try and set github status on this branch > 1000.  Github only allows 1K status updates for any given commit sha.  I will continue to look into this, but at the moment I have no idea what went wrong.

This commit/PR is effectively **dead** from a CI testing stand point.  You will need to create a new PR if you want CI to work.

**Comment by tasleson** [comment]
@cathay4t Do you have any node side logs which could tell me what the heck was going on with the node?

**Comment by cathay4t** [comment]
@tasleson I will email you the login information to that node for your investigation.

**Comment by tasleson** [comment]
@cathay4t Missing spec file update.  Have you run coverity scans?

**Comment by tasleson** [comment]
@cathay4t I ran coverity scans, they look good.

**Comment by cathay4t** [comment]
@tasleson Thanks. RPM spec changelog included.

**Comment by tasleson** [comment]
:+1:  LGTM

**Comment by cathay4t** [comment]
Merged.

**Pull request merged**
