### PR TITLE
[PATCH V3] Add disk VPD83 query support.

### PR DESCRIPTION
**Pull request by cathay4t**
New library level  functions:
```
// C
int lsm_scsi_vpd83_of_disk_path(const char *sd_path,
                                const char **vpd83,
                                lsm_error **lsm_err);
# Python
vpd83 = lsm.SCSI.vpd83_of_disk_path(sd_path)
```

New Client API functions:
```
// C
const char *lsm_disk_vpd83_get(lsm_disk *d);

# Python
lsm.Disk.vpd83
```

New plugin API functions:
```
// C
int lsm_disk_vpd83_set(lsm_disk *disk, const char *vpd83);

# Python
lsm.Disk.__init___(..., _vpd83=<vpd83>)
```

New capability:
```
C:         LSM_CAP_DISK_VPD83_GET
Python:    lsm.Capabilities.DISK_VPD83_GET
```
Based on pull request #71 and #76 , please review them first.

### CODE REVIEW

**Comment by cathay4t** [comment]
@joehandzik Could you help me by test this patch set on your JBOD HPSA cards?

Expecting output of `lsmcli ld --uri hpsa://` would contain valid "SCSI VPD 0x83 " and "Disk Paths"

**Comment by tasleson** [comment]
@cathay4t The travis CI failures and the actual array test failures are different.

**Comment by joehandzik** [comment]
@cathay4t 'make check' failed on my box, but your requested test does indeed have /dev/sd<> paths along with VPD 0x83. Nice!!

**Comment by tasleson** [comment]
Today the python packages are not arch specific.  By creating a python module in C they will be arch specific.  For this change to work we are going to need a separate sub package for this new bit of functionality to keep the arch specific and arch non-specific bits isolated.

**Comment by cathay4t** [comment]
Thank you both.
I will look into issue you guys mentioned.

**Comment by tasleson** [comment]
@cathay4t FYI: I haven't gotten all the way through my code review, will review more next week.

**Comment by cathay4t** [comment]
Please hold.
`_udev_vpd83_of_sd_name()` and  `_udev_vpd83_of_sd_name()` should return `LSM_ERR_NOT_FOUND_DISK` when disk not found, instead of `NO_SUPPORT`.

This cause `make check` failed on server without '/dev/sdb'.

**Comment by cathay4t** [comment]
V2 patch set uploaded.

Changes in V2:
* Return `LSM_ERR_NOT_FOUND_DISK` when provided `sd_path` is not found in sysfs.
* Fixed typo.

**Comment by tasleson** [comment]
Reviewed last 7 commits of this PR.  Looks good except for the same static variable usage in shared library.  Re-work that and this will be ready.

**Comment by cathay4t** [comment]
V3 patch set uploaded.

Changes in V3:
* Replace library static variable `_lsm_err_msg` with function local variable `char err_msg`.

**Comment by tasleson** [comment]
Looks good, thanks!

**Pull request merged**
