### PR TITLE
419: support new encryption information in the ssacli report for hpsa plugin

### PR DESCRIPTION
**Pull request by cstoyanov-scality**
Signed-off-by: STOYANOV Christophe <christophe.stoyanov@scality.com>

CI restart.

### CODE REVIEW

**Comment by tasleson** [comment]
resolves: https://github.com/libstorage/libstoragemgmt/issues/419

**Comment by tasleson** [comment]
@cstoyanov-scality Have you been able to run all the unit tests for the hpsa plugin?  At the moment I don't have access to test hardware for this and would like to make sure we don't introduce a regression.

**Comment by cstoyanov-scality** [comment]
@tasleson I have executed the whole testsuite in test/ and the different checks given in the documentation. It succeeds in. Is there a way to generate a short report?

**Comment by tasleson** [comment]
@cstoyanov-scality The main test I'm thinking of is `plugin_test.py`.  We don't require proof of running, but the output of that with `-v` is pretty short.  We have the ability to utilize remote hardware for CI testing.  If you're in a position to offer some hardware that is available for use we could add it to the automated github CI that runs now.  If this sounds interesting, please email me for details.  The source code for what provides the distributed CI is here: https://github.com/tasleson/lsm-ci .  It would be great to have at least one test node available for each type of hardware we support.

**Comment by tasleson** [comment]
@cstoyanov-scality Thanks!

**Pull request merged**
