### PR TITLE
DEMO: Provide lsmcli command for local disk RAID query functions.

### PR DESCRIPTION
**Pull request by cathay4t**
**DEMO yet. Don't commit.**

New lsmcli command for:
    * Provide RAID information on specified /dev/sdX.
    * Provide physical disk information on specified /dev/sdX.

### CODE REVIEW

**Comment by cathay4t** [comment]
The output of the new commands:

```

[fge@megadeth lsmcli]$ sudo lsmenv local lsmcli local-phy-disk-info --path /dev/sdb
Device alias: local
URI: local://
lsmcli local-phy-disk-info --path /dev/sdb
ID              | Name                               | Type | Size          | Status | System ID  | SCSI VPD 0x83    | Disk Paths | Revolutions Per Minute        | Link Type
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
WD-WCAVY0515921 | Disk 10 ATA WDC WD2002FYPS-01U1B0  | SATA | 1999844147200 | Error  | SV51929674 | 50014ee2adbe9932 |            | Rotating Medium Unknown Speed | PATA/SATA
WD-WX21E943H5KR | Disk 17 ATA WDC WD5000LPCX-22VHAT0 | SATA | 499558383616  | OK     | SV51929674 | 50014ee605a7ec0a |            | Rotating Medium Unknown Speed | PATA/SATA

Time: 0:08.05

[fge@megadeth lsmcli]$ sudo lsmenv local lsmcli local-raid-info --path /dev/sdb
Device alias: local
URI: local://
lsmcli local-raid-info --path /dev/sdb
Volume ID                        | RAID Type | Strip Size | Disk Count | Minimum I/O Size | Optimal I/O Size
------------------------------------------------------------------------------------------------------------
600605b00a579620214d6127faf57d4e | RAID0     | 262144     | 2          | 262144           | 524288          

Time: 0:05.78
```

**Comment by cathay4t** [comment]
@joehandzik Any input on these new lsmcli commands?

**Comment by joehandzik** [comment]
@cathay4t Apologies for sitting on this for so long. These look great!

**Comment by cathay4t** [comment]
Closing. Will move this kind of functions to 'tools/user_cases' folder.

**Pull request closed without merging**
