### PR TITLE
Query local disk LED status

### PR DESCRIPTION
**Pull request by cathay4t**
~~**Don't commit, need to rebase after PR #233**~~

Python API: `lsm.LocalDisk.led_status_get()`
C API: `lsm_local_disk_led_status_get()`
lsmcli: `lsmcli ldl` includes the disk LED status in script mode. Example:

```
---------------------------------------------------------
Path                   | /dev/sdai                       
SCSI VPD 0x83          | 50014ee2b5888597                
Revolutions Per Minute | 5400                            
Link Type              | PATA/SATA                       
Serial Number          | WD-WCC4JHAZ412D                 
LED Status             | FAULT_OFF,IDENT_OFF             
---------------------------------------------------------
```
The original PR is #217, but github refuse to reopen that one as I override my branch.

### CODE REVIEW

**Comment by cathay4t** [comment]
@joehandzik Any chance to try this on hpsa enclosure?

**Comment by joehandzik** [comment]
@cathay4t I did test this right after you submitted the PR, it worked perfectly! If you're confident that you didn't change the logic via refactoring, then we're probably good to check this in. If you'd rather wait until I get a chance to sanity test one more time, it'll need to wait until next Monday...I'm OoO away from my servers today, and tomorrow is the start of Thanksgiving here in the US.

**Comment by cathay4t** [comment]
@joehandzik Sure. Happy shopping :)

**Comment by joehandzik** [comment]
@cathay4t LGTM on my DL380 Gen9, you're clear to merge when you're ready.

For the record, no excessive shopping was done on my watch!

**Comment by tasleson** [comment]
@cathay4t @joehandzik Thanks guys!

**Pull request merged**
