### PR TITLE
[PATCH V2 0/8] Adding new system property: system mode.

### PR DESCRIPTION
**Pull request by cathay4t**
Adding new system property: `lsm.System.mode` and `lsm_system_mode_get()`.
Please check patch for detail.

TODO: Need HP's help on hpsa plugin, the original HP patch #52 does not works
            works on my system.

### CODE REVIEW

**Comment by cathay4t** [comment]
@joehandzik could you check the hpsa plugin patch?
Issues:
1. 'HBA Mode Enabled' does not exist on my system(hpssacli-2.30-6.0.x86_64).
2. If we use 'Controller Mode' instead, please advice the possible value of that property.

**Comment by joehandzik** [comment]
Ah, thanks for pointing that out. I’ll take a look and see what the best alternative is…I’m testing on a Gen9 controller, but it’s good to know that a Gen8 controller (I assume?) yields different output. Best to design around both.

Alternatively, we could do a sets for the attribute, and if it doesn’t exist, the controller is assumed to be in RAID mode.

Joe

**Comment by cathay4t** [comment]
@joehandzik Just FYI. The system I am using is Gen9:
```
[fge@megadeth ~]$ lspci|grep Gen
03:00.0 RAID bus controller: Hewlett-Packard Company Smart Array Gen9 Controllers (rev 01)
[fge@megadeth ~]$ sudo lsmenv hpsa lsmcli ls 
Device alias: hpsa
URI: hpsa://
lsmcli ls
ID             | Name                       | Status | Info | FW Ver | Mode   
------------------------------------------------------------------------------
PDNNF0ARH6W07M | Smart Array P840 in Slot 1 | OK     |      | 2.14   | HW RAID

Time: 0:02.46
```

**Comment by joehandzik** [comment]
That's unexpected. I didn't realize output would be so different between our H series controllers and P series controllers. Thanks for the info!

**Comment by cathay4t** [comment]
* Updated definition to hold LSI MegaRAID JBOD mode[1].
* Updated MegaRAID plugin.


[1]: LSI MegaRAID JBOD mode allows both logical disk and physical disk exposed to OS.

**Comment by tasleson** [comment]
@cathay4t PR looks good, just a few things.  Any updates on SmartArray, your comment indicates we don't have a workable solution at the moment?

**Comment by joehandzik** [comment]
@tasleson Sort of. The implementation I went with initially for Smart Array doesn't work on @cathay4t's Gen9 RAID controller (I was using a Gen9 HBA). Ideally, the hpssacli developers wouldn't have changed the basic templated output between H and P series controllers, but it looks like they did. They have a few attributes that tell you if the controller is in HBA or RAID mode, we'll just need to go with the one that is common between H and P series (which @cathay4t already identified). I'm on the hook for figuring out possible output values...I'll give him my output when in HBA mode, and we'll have enough for an initial implementation between my HBA mode output and his RAID mode output.

**Comment by joehandzik** [comment]
@cathay4t, with an H240, I have:

  Controller Mode: HBA

I'm assuming you have:

  Controller Mode: RAID

?

**Comment by cathay4t** [comment]
@joehandzik Yes. I will change the patch to use "Controller Mode" property. Thanks.

**Comment by cathay4t** [comment]
V2 patch set uploaded.

Changes in V2:

* Fix typo mentioned by Tony. Thanks, Tony.
* Updated SmartArray plugin to use "Controller Mode" to detect system mode.

**Comment by cathay4t** [comment]
@joehandzik Could you please give it a try on your hardware for HBA mode?
I don't have a SmartArray which could[1] configure as HBA mode.
Thank you.


[1]: The server I have is booting from SmartArray, converting to HBA mode requires OS reinstall
      which I would rather not to do so.

**Comment by joehandzik** [comment]
Yup, I'll give it a shot tomorrow!

Joe

On Oct 20, 2015, at 8:26 PM, Gri Ge <notifications@github.com<mailto:notifications@github.com>> wrote:


@joehandzik<https://github.com/joehandzik> Could you please give it a try on your hardware for HBA mode?
I don't have a SmartArray which could[1] configure as HBA mode.
Thank you.

[1]: The server I have is booting from SmartArray, converting to HBA mode requires OS reinstall
which I would rather not to do so.

�

**Comment by cathay4t** [comment]
@joehandzik Any update?

**Comment by joehandzik** [comment]
Just tried it, works perfectly (result was the expected value "HBA" for my device)! Sorry for the delay.

**Comment by cathay4t** [comment]
Merged. Thanks.

**Pull request merged**
