### PR TITLE
move list call to the right level, fixes #251

### LINKED ISSUE #251: python3 support typo in the hpsa plugin
In volume_raid_create, a call to list was added at the wrong level in an expression:
`sys_id = list(_sys_id_of_ctrl_data(sys_output.values()[0]))`
Should be:
`sys_id = _sys_id_of_ctrl_data(list(sys_output.values())[0])`
This causes a wrong pool id to be searched for (`['P', 'D', 'S', 'X', 'L', '0', 'B', 'R', 'H', '7', 'V', '0', '8', 'J']:Array:D`) and the method fails.

### PR DESCRIPTION
**Pull request by cvedel**
Note: Repo added to trusted.

### CODE REVIEW

**Comment by joehandzik** [comment]
@tasleson @cathay4t We're working with @cvedel at Scality, any concerns about me adding him to the trusted repo list?

**Comment by joehandzik** [comment]
PR #253, FYI

**Comment by joehandzik** [comment]
@tasleson Do we actually have python 3 CI working yet? I forget. If not, this PR going in pretty much depends on @cvedel confirming that it works. Working to get the HPE server added back into CI, and probably need to pull in a second server for RAID mode since the issues @cvedel is likely to find will be RAID mode specific.

**Comment by tasleson** [comment]
@joehandzik I remember working on making the plugin tests running both py2 & py3, but at the moment I'm not sure anymore.

**Comment by tasleson** [comment]
@joehandzik Yes, the `ci_unit_test.sh` that I distributed has python2 and python3 testing in it.  Assuming you are running the latest then your test node should be testing both each time.

**Comment by tasleson** [comment]
@joehandzik @cathay4t Please make sure your `ci_unit_test.sh` matches this one: https://github.com/tasleson/lsm-ci/blob/master/ci_unit_test.sh

**Comment by joehandzik** [comment]
@tasleson Ok, sounds good. Looks like this is just code that is only touched in RAID mode (I had configured in HBA mode because that was my priority at the time of integrating into CI). Going forward, I'm going to add that RAID box into the CI. I should have that version of the script, looks like the last time the code was touched was September.

**Comment by joehandzik** [comment]
@cvedel @tasleson @cathay4t Validated the fix manually on my end, but it requires another couple of patches that I will submit either this weekend or Monday. Pulling this in.

**Pull request merged**
