### PR TITLE
 Boost the test speed by changing sim plugin ASYN time

### PR DESCRIPTION
**Pull request by cathay4t**
* Change sim plugin asyn time to 0.1 seconds.
 * Test results by `make check`:
```
    new: 3m33.057s
    old: 5m36.745s
```

Signed-off-by: Gris Ge <fge@redhat.com>

### CODE REVIEW

**Comment by tasleson** [comment]
I'm OK with this as long as we get 1 or more job status checks in.

**Comment by cathay4t** [comment]
Got 3 or 4 job status check:
```
URI = sim://localhost/?statefile=/tmp/12680/plugin_data//lsm_sim_oshnivorzthbnznvgegnqhuezrzheto
System mode: (1)
URI = sim://localhost/?statefile=/tmp/12680/plugin_data//lsm_sim_unyivtwmuruwgvjbdqhriqlmsenzkho
HP SmartArray Plugin:1.3.0
LSI MegaRAID Plugin:1.3.0
NexentaStor support:1.3.0
NetApp Filer support:1.3.0
Storage simulator:1.3.0
Generic SMI-S support:1.3.0
Linux LIO target support:1.3.0
URI = sim://localhost/?statefile=/tmp/12680/plugin_data//lsm_sim_humrshpecgaaovlrzbysmrdylkokwva
VOLUME: Job JOB_ID_00001 in progress, 253 done, status = 1
VOLUME: Job JOB_ID_00001 in progress, 46 done, status = 1
VOLUME: Job JOB_ID_00001 in progress, 97 done, status = 1
VOLUME: Job JOB_ID_00001 in progress, 100 done, status = 2
Volume complete: Job JOB_ID_00001 percent 100 done, status = 2, rc=0
GENERIC: Job JOB_ID_00001 in progress, 1 done, status = 1
GENERIC: Job JOB_ID_00001 in progress, 52 done, status = 1
GENERIC: Job JOB_ID_00001 in progress, 100 done, status = 2
```

**Comment by tasleson** [comment]
OK, that is good.  However, this looks very wrong:

`VOLUME: Job JOB_ID_00001 in progress, 253 done, status = 1`

**Comment by tasleson** [comment]
Thanks @cathay4t

**Pull request merged**
