### PR TITLE
Misc cmdtest fixes

### PR DESCRIPTION
**Pull request by tasleson**
Test kick!

### CODE REVIEW

**Comment by Mashimiao** [comment]
LGTM

**Comment by tasleson** [comment]
@cathay4t Have you seen the travis-ci failure before?

**Comment by cathay4t** [comment]
@tasleson That's `LSM_ERR_NO_MEMORY`. Quite rare. Still checking.

**Comment by cathay4t** [comment]
LGTM.

@tasleson Could do some trivial force push to let travis run test again?

**Comment by tasleson** [comment]
@Mashimiao @cathay4t  Thanks for the reviews!

**Pull request merged**
