### PR TITLE
Enable GCC warnings and fix found warnings.

### PR DESCRIPTION
**Pull request by cathay4t**
* Enable GCC `-Wall`, `-Werror` and `-Wextra` flags.

Note: Testing CI

### CODE REVIEW

**Comment by cathay4t** [comment]
@joehandzik Is this PR fit your expectation of https://github.com/libstorage/libstoragemgmt/pull/207#issuecomment-260692352 ?

**Comment by cathay4t** [comment]
Don't commit yet. I missed the python3 part.

**Comment by cathay4t** [comment]
Python3 fixed.

**Comment by joehandzik** [comment]
@cathay4t Yeah, this looks like what I wanted! I'll give a more detailed code review later today.

**Comment by cathay4t** [comment]
@tasleson Could you take a look on 3par and nstor CI failure when you got some time? Thank you.

**Comment by tasleson** [comment]
@cathay4t  I took a peek and was kind of confused because the logs showed the latest runs were completing successfully.  I waited for the hitachi to finish and then edited the text to the PR which caused another test run which ran cleanly across all.

**Comment by cathay4t** [comment]
@tasleson OK. Let's investigate when it show up again.

**Comment by tasleson** [comment]
@cathay4t See https://github.com/libstorage/libstoragemgmt/issues/234 .  I wasn't looking far enough back in the history.

**Comment by cathay4t** [comment]
@tasleson @joehandzik Are we OK to merge this one?

**Comment by joehandzik** [comment]
@cathay4t I say yes.

**Comment by tasleson** [comment]
@cathay4t  Thanks Gris!

**Pull request merged**
