### PR TITLE
Use pyudev to obtain sysfs attributes.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Another attempt to introduce pyudev dependency in libstoragemgmt.

The PR is incomplete, I didn't want to go any further with it unless it was at least a possibility.

Also, I'm not sure that using fallback values is really the right choice if the device doesn't exist at all, but that possibility didn't need to be addressed in the original source, so I do not know what is best.

**Comment by joehandzik** [comment]
It's certainly cleaner, no arguments from me. If @cathay4t and @tasleson accept this, I'll rework mine the same way.

**Comment by joehandzik** [comment]
@mulkieran I can't think of a reason why hpssacli would expose the volume but the host wouldn't have a sysfs path to it. Honestly, if that sort of thing is happening it doesn't matter (from my perspective) what values are present in any attributes, because we're already in crazy-town.

**Comment by mulkieran** [comment]
@joehandzik It ought to be unlikely. I do a lot of CI with pyudev with tests drawn from the existing environment and I have seen it happen where the test fails because the device being tested disappeared. So I see these kinds of things more than most people.

**Comment by joehandzik** [comment]
@mulkieran I suppose it's fair that the device could disappear after the python object has been instantiated...not so unusual in my experience either. Any ideas for better error detail?

**Comment by cathay4t** [comment]
@mulkieran Thanks for the PR. Please add `python-pyudev` package into `.travis.yml`.
Meanwhile, could you provide test results on old system like RHEL 6?

**Comment by mulkieran** [comment]
@cathay4t .travis.yml done. I'm not sure how I would go about getting satisfactory test for RHEL6, you'll have to advise me on that.

**Comment by cathay4t** [comment]
@mulkieran Let me do that test by reserving a hpsa server in RHEL 6 from our internal beaker lab.

**Comment by cathay4t** [comment]
@mulkieran Please update RPM spec file for dependency also. Thanks!

**Comment by mulkieran** [comment]
@cathay4t spec file updated. My original code had a major bug that should definitely have raised an exception if it had been executed. I guess the CI tests aren't able to test the actual functionality of the plugins?

**Comment by tasleson** [comment]
@mulkieran The unit tests only test the code against the simulators and the nstor and targetd boxes we have.  We can certainly add more boxes, but we need the hardware and CI service running to utilize, something we have been meaning to do.

**Comment by mulkieran** [comment]
@tasleson Thanks, that makes sense. Is there any code in the repo for those two plugin tests? I'm not finding it, but maybe I don't know how to look.

**Comment by tasleson** [comment]
@mulkieran We have test/plugin_test.py which runs against plugins.  You should be able to run that on a system that has the hardware needed to exercise the plugin(s).

**Comment by tasleson** [comment]
@mulkieran Any update on running the test on actual hardware?

**Comment by joehandzik** [comment]
@tasleson @mulkieran Seems like maybe this should be me, what with me having ten ProLiant servers of my own in a rack 30 feet away from me and all...let me schedule some cycles to do the testing this week. Sound fair?

**Comment by tasleson** [comment]
@joehandzik Sounds fair to me, Thanks!

**Comment by mulkieran** [comment]
@joehandzik Thanks!

**Comment by joehandzik** [comment]
'lsmcli -lv' gives me the right size answer, which is based on two of the attributes you're pulling out of sys. I call it good!

**Comment by tasleson** [comment]
@joehandzik Would it be possible to run the `test/plugin_test.py` ?

**Comment by joehandzik** [comment]
@tasleson T'was the first thing I did, it passed all 'make check' tests. I did only test Rhel7 though, so good call on testing Rhel6.

**Comment by joehandzik** [comment]
@tasleson Passed, ran 42 tests in ~70 seconds.

**Comment by tasleson** [comment]
@joehandzik `make check` only does tests against the simulators, C & Python.  To test against a piece of hardware we use the `test/plugin_test.py`.  You would need to make sure that a pool exists before hand to allow the test the ability to create things.  I've not actually run the test myself against hardware, but @cathay4t has.

**Comment by joehandzik** [comment]
@tasleson Yeah, I realized my error a few minutes ago. See my updated comments above.

**Comment by tasleson** [comment]
@joehandzik great, thanks!

**Comment by cathay4t** [comment]
@mulkieran Please update `configure.ac` to check `pyudev` module. This line might helps:
```
AC_PYTHON_MODULE([pyudev], [Required])
```

Besides that, RHEL 6 test on hpsa works well.

**Comment by tasleson** [comment]
@mulkieran @joehandzik @cathay4t Thanks everyone for the improvement!

**Pull request merged**
