### PR TITLE
HPE Smart Array: Return STATUS_OK when a cache module reports as unconfigured

### PR DESCRIPTION
**Pull request by joehandzik**
Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

### CODE REVIEW

**Comment by joehandzik** [comment]
Fixes #144

**Comment by joehandzik** [comment]
One thing to note here is that this refactor is pulling a status_info now for the SYSTEM_OK status. Is that going to be a problem? If so, it can be fixed pretty easily by pulling the status_info population into the appropriate if branches.

**Comment by cathay4t** [comment]
@joehandzik If 'not configured' only means no volumes are using cache in HPE SmartArray. How about we just treat it as SYSTEM_OK?

I got a system with only 2 ssd disks as RAID1 volume, with SmartPath enabled, RAM cache will be disabled. With this configure, I got 'no configure' cache status.
IMHO, this configure is OK and healthy, showing it as 'SYSTEM_UNCONFIGURED' sounds like user attention needed.

**Comment by joehandzik** [comment]
@cathay4t I see your point, but calling it SYSTEM_OK loses some of the detail around the actual status. Maybe a compromise? I'll switch it to SYSTEM_OK for this config, but I'll continue to collect status_info for SYSTEM_OK statuses too. That way, a user could find out that the cache is actually unconfigured if they look in the right place.

**Comment by joehandzik** [comment]
@cathay4t Compromise implemented here. Lemme know if you want it changed, otherwise this should cover your requirements and mine.

**Comment by tasleson** [comment]
@joehandzik  @cathay4t System status is a bitfield, we can express that it's OK and that something else is true too.

**Comment by tasleson** [comment]
@joehandzik Your latest commit comment doesn't match what the code change is.

**Comment by joehandzik** [comment]
Yikes, you're very right. Will fix as soon as I can.

Joe

On May 11, 2016, at 10:41 AM, Tony Asleson <notifications@github.com<mailto:notifications@github.com>> wrote:


@joehandzik<https://github.com/joehandzik> Your latest commit comment doesn't match what the code change is.

-

**Comment by joehandzik** [comment]
@tasleson Ok, finally got the mismatched commit messaging addressed. 

It looks like we handle bitmaps correctly in the cli (from a quick glance, anyway), is there anywhere else we'd need to be concerned about? I'm fine with this not being in both an OK state and an unconfigured state for now, but we might want to think about it for 1.4.

**Comment by tasleson** [comment]
@joehandzik The code should be handling bitfields, I don't know of any reasons why we should be concerned.

**Comment by tasleson** [comment]
@joehandzik Thanks!

**Pull request merged**
