### PR TITLE
Misc fixes found by Fedora rawhide gcc

### PR DESCRIPTION
**Pull request by cathay4t**
* Should use strlen() instead of sizeof() for calculate string length.
 * Fix the gcc warning on fallthrough switch.

### CODE REVIEW

**Comment by tasleson** [comment]
@cathay4t Did you grep the code to ensure this wasn't done anywhere else too?

**Comment by cathay4t** [comment]
Already did so.

**Comment by cathay4t** [comment]
Please don't merge yet. Fedora rawhide found more issues.

**Comment by cathay4t** [comment]
Fedora rawhide rpm compile passed.

**Comment by cathay4t** [comment]
@tasleson Could you review these patches?

**Comment by tasleson** [comment]
LGTM, Thanks Gris!

**Pull request merged**
