### PR TITLE
MegaRAID plugin: Fake timeout support and add missing capability.

### PR DESCRIPTION
**Pull request by cathay4t**
- Fake timeout support in order to pass plugin test.
- Add missing `VOLUME_CACHE_INFO` capability.

Note: If you edit the pull request text section, you will get the unit tests to re-run.  Not sure if this is good or not, but it does help with testing CI infrastructure.

### CODE REVIEW

**Comment by cathay4t** [comment]
Don't commit this yet. I would like to keep this one for CI testing also.
Thanks.

**Comment by tasleson** [comment]
Gris, I used this PR for CI testing too by simply editing the PR text.  Please disregard the `CI run aborted` status.  It's an old status context I was using.  I changed it as you cannot delete a status, so to not confuse people I changed the context to 'CI permissions" and added a successful status too.  That way when a PR gets added to the trusted repo list the status will change from fail to success when the PR gets updated.

**Comment by cathay4t** [comment]
@tasleson After I removed the python3(RHEL 7 does not have python3) test scritps, the MegaRAID CI passed.

**Comment by tasleson** [comment]
@cathay4t Well it would be good to have a test environment where we can test each python plugin automatically with python2 & python3.

**Comment by cathay4t** [comment]
@tasleson I will follow up on that. The megaraid server is a share server, I need to check with other user about reinstalling to Fedora.

**Comment by cathay4t** [comment]
I will install a python3 server for megaraid testing this weekend. Please don't merge this PR yet.

**Comment by cathay4t** [comment]
@tasleson MegaRAID CI is ready for python2 and python3.

**Comment by tasleson** [comment]
@cathay4t Great, thank you!

**Comment by cathay4t** [comment]
@tasleson Are we OK to merge this? The CI failure is caused by a removed test node.

**Comment by tasleson** [comment]
@cathay4t Thanks!

**Pull request merged**
